server:
  port: 8080

spring:
  application:
    name: "arquetipo-arquitetura-hexagonal"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/testDB"
    username: "postgres"
    password: "<SENHA AQUI>"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    format-sql: true

logging:
  level:
    root: info